### ISSUE TITLE
Ardour4 - segmentation fault

### ISSUE THREAD

**Issue by sc3sc3** [harryhaaren/openAV-ArtyFX#15]
Is it possible the plugins are not compatible with Ardour4 ?

I just compiled them on ubuntustudio 14.04.
When I add for example Roomy and try to open its ui,
Ardour crashes with a segmentation fault, nothing more is logged in prompt.

Regards
sc3

**Comment by harryhaaren** [comment]
Hi @sc3sc3,

There are no known issues with Ardour4 and ArtyFX - perhaps you could test Roomy in Jalv[1] using a terminal?
```
jalv.gtk `lv2ls | grep roomy`
```
If that also fails, then there is probably and ArtyFX issue, but most likely that will work, and the next step would be to ask the Ardour guys if they've seen this issue before.

Cheers, -Harry

[1] probably: sudo apt-get install jalv

**Comment by sc3sc3** [comment]
Hi Harry,

that works fine indeed.

I'm using build
Ardour 4.2.84+r13306
"Taking Tiger Mountain"
(built from revision 4.2.84+r13306.23)
Intel 64 bit

Shall I mention this then on Ardour forum ?

Thanks
sc3

**Comment by harryhaaren** [comment]
Hi,

Yes they'll need all the information I'd guess. Try their IRC channel otherwise - people generally respond within 20 mins, so hang around a few minutes after posting your issue. #ardour on irc.freenode.net. Join the IRC room online here: http://webchat.freenode.net/?randomnick=1&channels=%23ardour&uio=MTY9bnVsbAe6 

Usually a "step-by-step" process on making the bug happen is really useful too. Something like this probably:
```
1. Load ardour4 (version blah-blah)
2. Add a stereo audio track
3. Right click plugin area, load Roomy from ArtyFX (version blah blah)
4. Crash, no terminal output
```
Good luck, I'll mark this bug as closed now.

**Comment by sc3sc3** [comment]
I reported Ardour bug
http://tracker.ardour.org/view.php?id=6589

Thanks for your help.
